### ISSUE TITLE
ImportError: cannot import name 'PublicKey'

### ISSUE THREAD

**Issue by bitphage** [GolosChain/golos-python#18]
Circular import error

```
Python 3.6.1 (default, Sep  6 2017, 16:18:23) 
[GCC 5.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

>>> from steembase.account import Publickey
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vvk/devel/golos/golos-python/steembase/account.py", line 5, in <module>
    from steem.utils import compat_bytes, compat_chr
  File "/home/vvk/devel/golos/golos-python/steem/__init__.py", line 2, in <module>
    from .steem import Steem
  File "/home/vvk/devel/golos/golos-python/steem/steem.py", line 1, in <module>
    from .commit import Commit
  File "/home/vvk/devel/golos/golos-python/steem/commit.py", line 10, in <module>
    from steembase import memo
  File "/home/vvk/devel/golos/golos-python/steembase/memo.py", line 10, in <module>
    from .operations import Memo
  File "/home/vvk/devel/golos/golos-python/steembase/operations.py", line 8, in <module>
    from .account import PublicKey
ImportError: cannot import name 'PublicKey'
>>> 
```

**Comment by crokkon** [comment]
workaround: import `Steem` first
```
>>> from steem import Steem
>>> from steembase.account import PublicKey
```
