### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by bitfag** [GolosChain/golos-python#3]
Sometimes while performing `Steem.transfer()` I'm getting the following non-informative error message:

```
Traceback (most recent call last):
  File "./otkat.py", line 165, in main
    transfer(golos, conf['account'], voter, payout_rounded, memo)
  File "./otkat.py", line 34, in transfer
    steem_instance.transfer(to, amount, 'GBG', memo=memo, account=account)
  File "/home/vvk/devel/golos/otkat-py/venv/lib/python3.6/site-packages/steem/commit.py", line 607, in transfer
    return self.finalizeOp(op, account, "active")
  File "/home/vvk/devel/golos/otkat-py/venv/lib/python3.6/site-packages/steem/commit.py", line 119, in finalizeOp
    tx.appendOps(ops)
  File "/home/vvk/devel/golos/otkat-py/venv/lib/python3.6/site-packages/steem/transactionbuilder.py", line 42, in appendOps
    self.constructTx()
  File "/home/vvk/devel/golos/otkat-py/venv/lib/python3.6/site-packages/steem/transactionbuilder.py", line 84, in constructTx
    ref_block_num, ref_block_prefix = get_block_params(self.steemd)
  File "/home/vvk/devel/golos/otkat-py/venv/lib/python3.6/site-packages/steembase/transactions.py", line 332, in get_block_params
    ref_block_prefix = struct.unpack_from("<I", unhexlify(ref_block["previous"]), 4)[0]
TypeError: 'NoneType' object is not subscriptable
```

I think we need to investigate the root cause of such failures and provide a more clear error message to library users.

**Comment by bitfag** [comment]
This looks like a persistent problem introduced in https://github.com/steemit/steem-python/pull/18/files
I reverted this change back to previous version originating from piston-lib and I not getting errors anymore.

**Comment by bitfag** [comment]
Use https://github.com/bitfag/piston-lib/tree/golos-fixes
Well-tested with 0.16.4.
